### PR TITLE
Add collection-related endpoints

### PR DESCRIPTION
**Pull request by gsfr**
I have added the basic structure for querying collections, including two new endpoints for getting collection acquisitions.

Zero tests. 👎 

@kofalt Could you please help me drive this home?

### CODE REVIEW

**Comment by kofalt** [comment]
I think there's a few problems with this struct:

```go
type Collection struct {
	Id          string `json:"_id,omitempty"`
	Name        string `json:"label,omitempty"`
	GroupId     string `json:"group,omitempty"`
	Description string `json:"description,omitempty"`

	Created  *time.Time `json:"created,omitempty"`
	Modified *time.Time `json:"modified,omitempty"`
	Files    []*File    `json:"files,omitempty"`

	Notes []*Note                `json:"notes,omitempty"`
	Tags  []string               `json:"tags,omitempty"`
	Info  map[string]interface{} `json:"info,omitempty"`

	Public      *bool         `json:"public,omitempty"`
	Archived    *bool         `json:"archived,omitempty"`
	Permissions []*Permission `json:"permissions,omitempty"`
}
```

1. Are you sure `group` is a valid field?
1. I don't see a `curator` field.
1. More? Are we sure collection fully extends container? Tags, for example.

From playing in the UI:

```js
{
    "_id" : ObjectId("59359bd4682642001e7485bf"),
    "created" : ISODate("2017-06-05T17:58:44.933Z"),
    "curator" : "nathanielkofalt@flywheel.io",
    "modified" : ISODate("2017-06-05T17:59:29.150Z"),
    "label" : "Wat",
    "permissions" : [ 
        {
           // ...
        }
    ],
    "notes" : [ 
        {
            // ...
        }
    ],
    "description" : "Hello world",
    "files" : [ 
        {
           // ...
        }
    ]
}
```

https://github.com/scitran/core/wiki/Data-Model#collection-extends-container
https://github.com/scitran/core/wiki/Data-Model#container

**Comment by kofalt** [comment]
When you run the tests, you'll notice it generates a `coverage.html` file.
Pop this open to have a look at the test coverage for your new source code.

I've added some basic tests that cover a few functions, which gets us to 36%.

Use the examples provided in that new test file & other sibling files to cover all functions except the bridge-only `UploadFileToCollection` and `DownloadFileFromCollection` ones.

**Comment by gsfr** [comment]
Thanks for your contributions and advice, @kofalt. The struct is a straight copy from Project, and hence wrong, which didn't manage to catch my attention until now.

Hoping to steal another hour from you later this week.

**Comment by kofalt** [comment]
Rebased to snag a fix for a breaking API change; there are now only this-branch-relevant failures.

**Comment by kofalt** [comment]
:tada:

**Comment by gsfr** [comment]
👍

**Pull request merged**
