### PR TITLE
Simplify project structure - maybe?

### PR DESCRIPTION
**Pull request by gsfr**
When I was working on the python SDK, I tripped over the directory structure a few times, especially the final copy operation in `make.sh`.

This is an attempt to simplify the structure a bit.

@kofalt Note the `git clean -fdX` in `make.sh`. Clever, but not entirely risk free.

Good idea?

Also, can you please enlighten me on the naming convention used for `template.go.`? In particular, the trailing `.`.

### CODE REVIEW

**Comment by kofalt** [comment]
... Hmm, yeah, I don't hate this.

The original intention was to keep a separation between tracked and untracked (distributable) objects, but as you can see that wasn't super successful. I think I like your approach better.

I probably won't go with the git command, I prefer to leave VCS usage out of build scripting wherever possible. But everything else looks reasonable! I'll add a commit or two and merge.

To answer your question, the trailing dot is to prevent the go tooling ecosystem from considering that file as source code (because it's not). I could work around that special case in the root make script, but I don't want to - that make script has been through many revisions, it's reusable, and I like it that way :)

**Comment by gsfr** [comment]
Would you be open to naming the templates something like `<language>.tmpl`? Cause the `.py` file ain't really a python file, either.

**Comment by kofalt** [comment]
Let's go with `<language>.template.extension`. I like my editor using the right highlighting, the go template is just an unfortunate exception.

**Comment by gsfr** [comment]
Yes, I like that, too. Does your editor respect vim-style modelines, a la `// vim: filetype=go`?

**Comment by kofalt** [comment]
I don't think so. Probably a plugin.

**Pull request merged**
