### PR TITLE
Add method to query SDK version

### PR DESCRIPTION
**Pull request by kofalt**
New method to get the version of the SDK you're using:

python example

matlab example

@jenreiter: Could you LGTM the Matlab method?
@ryansanford: I set the SDK version to `1.0` for now; set to desired string in `sdk.go`, or LGTM it.

### CODE REVIEW

**Comment by jenreiter** [comment]
I will note that the first time I called the method, it did not return the version but looked like it was still working... After interrupting the command and trying again, it worked. I also exited and restarted Matlab. Using the method again after rebooting, it was successful. I cannot recreate the strange behavior that I encountered initially. Otherwise, this looks good to me. 

screen shot 2017-08-02 at 5 07 33 pm

**Comment by kofalt** [comment]
For what it's worth, in Matlab you can also just do `Flywheel.getSdkVersion()` as it's a static method.

**Comment by kofalt** [comment]
1. Sounds good; will update
2. Auto-generation only applies to member functions of `api.Client`. The version retrieval is not attached to that object; I want to keep the way we set version / build information consistent among Go projects. 
3. They already are integrated into the build script, but not currently used because we don't ship an SDK binary. I'll remove them for now.

**Comment by kofalt** [comment]
Comments addressed. Rebased and squashed so we don't have a commit with a misleading version :)

**Comment by ryansanford** [comment]
@kofalt LGTM. I will tag post-merge.

**Pull request merged**
