### PR TITLE
Fix 63: Added missing collection field to SearchResponse

### LINKED ISSUE #63: Add `collection` key to search response object
A collection search response has the following format:
```
  {
    "collection": {
      "label": "Collection Name",
      "curator": "<uid>",
      "created": "2017-11-21T05:51:03.018000+00:00"
    },
    "permissions": [
      {
        "access": "admin",
        "_id": "<uid>"
      }
    ]
  }
```

But when using `fw.search()` with `"return type": "collection"`, only the permissions array is returned.

### PR DESCRIPTION
**Pull request by ehlertjd**
Fixes #63.

@kofalt @nagem

### CODE REVIEW

**Comment by kofalt** [comment]
@lmperry @wandell Can you confirm this works for you? 

This should add the data you were missing when using `'return_type': 'collection'`.

**Comment by lmperry** [comment]
As written the result does not contain the collection id. Let's be sure that's there as well.

See: https://github.com/scitran/core/pull/1019

**Comment by ehlertjd** [comment]
Added missing id field.
@kofalt @lmperry

**Comment by lmperry** [comment]
Thanks. LGTM!

**Pull request merged**
