### PR TITLE
Six (code for py2 and py3)

### LINKED ISSUE #1: Add python 2/3 support to python frontend
Right now, if you use the python SDK in python 3 you'll get some unicode errors. I don't know a ton about the language differences, but I assume it should be straightforward to produce code that's 2/3 compatible.

### PR DESCRIPTION
**Pull request by gsfr**
We should now have python2 and python3 compatibility. Closes #1.

Couldn't stop myself from re-indenting the python code. Hence, the diff is best viewed with `w=1`.

Replaces #4.

### CODE REVIEW

**Comment by kofalt** [comment]
There was a breaking API change that caused our tests to fail.
Fixed on master; please rebase :slightly_smiling_face:

**Comment by gsfr** [comment]
Rebased.

**Comment by kofalt** [comment]
```
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
Exited with code 1
```

Looks like the API crashed, retrying CI :/

**Comment by kofalt** [comment]
Alright, after much ado CI is green. I'll have a look at this properly in the afternoon.

**Comment by kofalt** [comment]
Out-of-band comments about caching the key object look good; ready to merge pending this working on py 3.6.

**Pull request merged**
